# Generated by Django 3.1.1 on 2020-09-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('email',), 'permissions': (('knowledge.view', 'View knowledge'), ('knowledge.create', 'Create knowledge'), ('knowledge.update', 'Update knowledge'), ('knowledge.delete', 'Delete knowledge'), ('user.view', 'View user'), ('user.create', 'Create user'), ('user.update', 'Update user'), ('user.delete', 'Delete user'), ('ontology.view', 'View ontology'), ('ontology.create', 'Create ontology'), ('ontology.update', 'Update ontology'), ('ontology.delete', 'Delete ontology'))},
        ),
    ]
